config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: "pages#splash"

  resources :users, only: [:index, :new, :create, :show, :destroy, :edit, :update] do
    resources :expenses, only: [:index, :new, :create, :show, :destroy, :edit, :update, :all]
    resources :categories, only: [:index, :new, :create, :show, :destroy, :edit, :update]
  end

  resources :expenses, only: [:index, :all] do
    collection do
      get :most_recent
      get :most_ancient
    end
  end

  resources :categories, only: [:index, :new, :create, :show, :destroy, :edit, :update]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/category.rb
class Category < ApplicationRecord
  after_initialize :set_default_icon, if: :new_record?
  belongs_to :user
  has_many :group_entities
  has_many :expenses, through: :group_entities
  has_one_attached :icon

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validate :valid_icon_format

  before_validation :set_default_icon

  def self.descending_order_for_user(user)
    where(user:).order(created_at: :desc)
  end

  private

  def valid_icon_format
    return unless icon.attached? && icon.blob.present?

    allowed_formats = %w[image/png image/gif image/jpeg image/jpg image/svg+xml]
    return if allowed_formats.include?(icon.blob.content_type)

    errors.add(:icon, 'Field only accepts png, gif, jpeg, jpg, or svg.')
  end

  def set_default_icon
    self.icon ||= 'icon-home.png'
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[new create]
  before_action :set_category, only: %i[show edit update destroy]

  def index
    # @user = User.find(params[:user_id])
    @categories = Category.includes(:expenses).where(user_id: current_user.id)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
  end

  # GET /categories/new
  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /users/1/categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = @user

    if params[:category][:icon]
      uploaded_io = params[:category][:icon]
      @category.icon_data = uploaded_io.read
    end

    respond_to do |format|
      if @category.save
        format.html { redirect_to user_category_url(@user, @category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = current_user
    return if @user

    store_location
    redirect_to new_user_session_path, alert: 'You need to sign in or sign up before continuing.'
  end

  def store_location
    session[:return_to] = request.fullpath if request.get?
  end

  def after_sign_in_path_for(resource)
    session[:return_to] || super
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :user_id, :icon_data)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p class="mt-3">
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p class="mt-3">
    <h2><%= category.name %></h2>
    <%= image_tag(category.icon) if category.icon.attached? %>
  </p>

  <p class="mt-3">
    <strong>Created at:</strong>
    <%= category.created_at %>
  </p>

  <p class="mt-3">
    <strong>User:</strong>
    <%= category.user_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this category", user_category_path(category.user, category), class: "btn btn-light" %>
    <%= link_to "Edit this category", edit_user_category_path(category.user, category), class: "btn btn-light ml-2" %>
    <hr class="mt-4">
  <% end %>
</div>

app/views/categories/_form.html.erb
<br />
<div id="form-container" class="group-item form-item">
<%= form_with(model: [@user, @category], url: user_categories_path(@user), class: "contents", enctype: "multipart/form-data") do |form| %>
  <% if @category.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
<br>
<div class="mb-3">
  <%= form.label :icon, "Add image", class: "form-label" %>
  <%= form.file_field :icon, id: "formFileLg", class: "form-control form-control-lg" %>
</div>
  <br>
  <%= form.hidden_field :user_id, value: @user.id %>
  <div class="action">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>
<br />

app/views/categories/edit.html.erb
<div class="mx-auto w-100">
  <h1 class="font-weight-bold display-4">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Show this category", @category, class: "ml-2 btn btn-light" %>
  <%= link_to "Back to categories", categories_path, class: "ml-2 btn btn-light" %>
</div>

app/views/categories/index.html.erb
<div class="main-container">
  <% if notice.present? %>
    <p class="alert alert-success mb-3" id="notice"><%= notice %></p>
  <% end %>
  <div class="d-flex justify-content-between align-items-center">
    <div id="categories-container" class="w-100">
      <% @categories.each do |category| %>
        <div class="category-card">
        <section class="category-card-two">
        <div class="category-info">
          <% if category.icon_data.present? %>
            <%= image_tag "data:image/png;base64,#{Base64.encode64(category.icon_data)}", class:"home-icon" %>
          <%else%>
            <%= image_tag 'icon-home.png', class: "home-icon" %>
          <% end %>
          <div class="category-details">
            <li class="name-category"><%= link_to category.name, category_path(category) %></li>
             <p class="time-category"><%= category.created_at.strftime("%d %b %Y %H:%M") %></p>
          </div>
        </div>
          <div class="category-amount">
            <ul>
              <p><strong>  Expenses: <%= category.expenses.count.presence || 0 %></strong></p>
              <p><strong>  Amount $<%= category.expenses.sum(:amount).presence || 0 %></strong></p>
            </ul>
          </div>
      </section>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="Add-button">
    <%= link_to "ADD CATEGORY", new_user_expense_path(current_user), class: "btn btn-primary btn-custom text-center" %>
</div>

app/views/categories/new.html.erb
<div class="mx-auto w-100">
<h1 class="font-weight-bold display-4 text-center">New Category</h1>
<div class="d-flex justify-content-center">
<div class="w-120">
  <%= render "form", category: @category %>
</div>
</div>
<div class="d-none justify-content-center">
  <%= link_to "Back to categories", user_categories_path(@user), class: "ml-2 btn btn-light" %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="mx-auto w-100 d-flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="alert alert-success mb-3" id="notice"><%= notice %></p>
    <% end %>

    <h1 class="font-weight-bold display-4"><%= @category.name %></h1>
    <p><%= @category.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
    <% if @category.expenses.any? %>
      <% @category.expenses.each do |expense| %>
        <p>
          <%= expense.name %>: <%= expense.amount %>
        </p>
      <% end %>
    <% else %>
      <p>No expenses for this category</p>
    <% end %>

    <%= link_to "Edit this category", edit_user_category_path(@category.user, @category), class: "mt-2 btn btn-light" %>
    <div class="d-inline-block ml-2">
      <%= button_to "Destroy this category", user_category_path(@category.user, @category), method: :delete, class: "mt-2 btn btn-light" %>
    </div>
    <%= link_to "Back to categories", user_categories_path(@category.user), class: "ml-2 btn btn-light" %>
  </div>
</div>