config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: "pages#splash"

  resources :users, only: [:index, :new, :create, :show, :destroy, :edit, :update] do
    resources :expenses, only: [:index, :new, :create, :show, :destroy, :edit, :update, :all]
    resources :categories, only: [:index, :new, :create, :show, :destroy, :edit, :update]
  end

  resources :expenses, only: [:index, :all] do
    collection do
      get :most_recent
      get :most_ancient
    end
  end

  resources :categories, only: [:index, :new, :create, :show, :destroy, :edit, :update]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/_header.html.erb
<div class="w-100 navbar-container" style="background-color: #3778c3; color: white;">
<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-header" style="background-color: #3778c3; color: white; padding: 0; margin: 0;">
<div class="container-fluid navbar-list-container" style="padding: 0;">
<% unless user_signed_in? && (current_page?(new_user_expense_path(current_user)) || current_page?(new_user_category_path(current_user))) %>
  <button class="navbar-toggler float-left" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" style="color: white; background-color: #3778c3;">
    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="white" class="bi bi-list" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
    </svg>
  </button>
<% end %>
<div class="navbar-brand mx-auto" style="color: white;">
<% if user_signed_in? %>
 <div class="text-center">
  <% if current_page?(user_expenses_path(current_user)) || current_page?(most_recent_expenses_path) || current_page?(most_ancient_expenses_path) %>
    <p>EXPENSES</p>
  <% elsif current_page?(new_user_expense_path(current_user)) %>
    <p>NEW EXPENSE</p>
  <% elsif current_page?(user_categories_path(current_user)) %>
  <p>CATEGORIES</p>
  <% elsif current_page?(new_user_category_path(current_user)) %>
    <p>NEW CATEGORY</p>
  <% elsif current_page?(user_path(current_user)) %>
    <p>PROFILE</p>
  <% else %>
    <!-- Add more conditions here for other pages -->
  <% end %>
</div>
<% end %>
</div>
<% if user_signed_in? && current_page?(new_user_expense_path(current_user)) %>
<%= link_to "<", user_expenses_path(current_user), class: "ml-2 btn btn-light mobile-back-button float-left", style: "color: white;" %>
<% elsif user_signed_in? && current_page?(new_user_category_path(current_user)) %>
<%= link_to "<", user_categories_path(current_user), class: "ml-2 btn btn-light mobile-back-button float-left", style: "color: white;" %>
<% end %>
<% if user_signed_in? && current_page?(user_expenses_path(current_user)) %>
<div class="float-left image-container">
<%= link_to "#", class: "btn btn-light image-container" do %>
<%= image_tag 'search.svg', class: 'search-icon', alt: 'search' %>
<% end %>
</div>
<% end %>
    <div class="collapse navbar-collapse" id="navbarNav" style="background-color: #3778c3; color: white;">
      <ul class="navbar-nav nav-links-container">
        <% if user_signed_in? %>
        <li class="nav-item" id="image-profile">
          <%= link_to user_path(current_user), class: "nav-link" do %>
            <% if current_user.image.attached? %>
              <%= image_tag(url_for(current_user.image), alt: "Profile Image", style: "width: 50px; height: 50px; border: 2px solid #434b54; border-radius: 50%; margin-bottom:10px;") %>
            <% else %>
              <h5>PROFILE</h5>
            <% end %>
          <% end %>
        </li>
          <!-- Add additional links for logged-in users here -->
      <li class="nav-item dropdown ml-auto" id="dropdown-text">
      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        CATEGORIES
      </a>
      <ul class="dropdown-menu">
        <li class="nav-item">
          <%= link_to "Categories", user_categories_path(current_user), class: "nav-link", style: "color: grey;" %>
        </li>
        <li class="nav-item">
          <%= link_to "New Category", new_user_category_path(current_user), class: "nav-link", style: "color: grey;" %>
        </li>
      </ul>
    </li>
    <li class="nav-item dropdown" id="dropdown-text">
      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        EXPENSES
      </a>
      <ul class="dropdown-menu">
        <li class="nav-item">
          <%= link_to "Expenses", user_expenses_path(current_user), class: "nav-link", style: "color: grey;" %>
        </li>
        <li class="nav-item">
          <%= link_to "New Expense", new_user_expense_path(current_user), class: "nav-link", style: "color: grey;" %>
        </li>
        </ul>
      </li>
          <div class="logout-container">
          <ul class="navbar-nav" id="logout-container">
            <li class="nav-item" id="logout-btn">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-secondary", data: { confirm: "Are you sure you want to log out?" }, style: "color: white; border: 4px solid  antiquewhite" %>
            </li>
          </ul>
          </div>
        <% else %>
          <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active d-none d-lg-block", "aria-current": "page", style: "color: white; background-color: #3778c3;" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<% if user_signed_in? && (current_page?(user_expenses_path(current_user)) || current_page?(most_recent_expenses_path) || current_page?(most_ancient_expenses_path)) %>
  <div class="navbar-box most-button" style="text-align: right; background: #3778c3; color: #434b54; boder: none;">
    <%= link_to  "Most Recent", most_recent_expenses_path, class: "btn btn-light mostbtn #{'active' if current_page?(most_recent_expenses_path)}", style: "color: white;" %>
    <%= link_to "Most Ancient", most_ancient_expenses_path, class: "btn btn-light mostbtn #{'active' if current_page?(most_ancient_expenses_path)}", style: "color: white;" %>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "style.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "layouts/header" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
     <main class="Main-app-container">
      <%= yield %>
      </main>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </body>
</html>